Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png  
    - .gif
JWT:
  Secret: wuliann
  Issuer: go-toy
  Expire: 7200
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix: ''
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
RedisDB:
  Addr: 127.0.0.1:6379
  Password: ''
  DB: 0