info:
  contact: {}
  description: 玩起来！！！
  title: go-toy
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
        "1":
          description: fail
          schema:
            type: string
      summary: 登录
      tags:
      - user
  /api/ping:
    get:
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
      summary: 测试Ping
  /api/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
        "1":
          description: fail
          schema:
            type: string
      summary: 注册
      tags:
      - user
  /changePassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: 旧密码
        in: body
        name: oldPassword
        required: true
        schema:
          type: string
      - description: 新密码
        in: body
        name: newPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
        "1":
          description: fail
          schema:
            type: string
      summary: 修改密码
      tags:
      - user
  /getMenuList:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
        "1":
          description: fail
          schema:
            type: string
      summary: 获取角色菜单
      tags:
      - menu
  /getUserInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "0":
          description: ok
          schema:
            type: string
        "1":
          description: fail
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - user
swagger: "2.0"
