info:
  contact: {}
  description: 玩起来！！！
  title: go-toy
  version: "1.0"
paths:
  /api/login:
    post:
      parameters:
      - description: 用户名
        in: body
        name: user_name
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: 失败
          schema:
            type: string
        "1":
          description: 成功
          schema:
            type: string
      summary: 登录
      tags:
      - user
  /api/ping:
    get:
      produces:
      - application/json
      responses:
        "1":
          description: 成功
          schema:
            type: string
      summary: 测试Ping
swagger: "2.0"
